# Generated by Django 3.1.2 on 2020-10-03 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=255)),
                ('job_description', models.CharField(max_length=1000)),
                ('salary', models.IntegerField()),
                ('location', models.CharField(max_length=255)),
                ('skill1', models.CharField(max_length=255)),
                ('skill2', models.CharField(max_length=255)),
                ('skill3', models.CharField(blank=True, max_length=255, null=True)),
                ('deadline', models.DateField()),
                ('posted_date', models.DateField(auto_now_add=True)),
                ('jobCompany', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.companyprofile')),
            ],
        ),
    ]
